# Generated by Django 5.2.11 on 2026-02-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Action", "Action"),
                            ("Comedy", "Comedy"),
                            ("Drama", "Drama"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("English", "English"), ("Hindi", "Hindi")],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("trailer_url", models.URLField()),
                ("poster", models.ImageField(upload_to="posters/")),
                ("release_date", models.DateField()),
            ],
        ),
    ]
